# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('avatar_url', models.TextField()),
                ('gravatar_id', models.TextField()),
                ('url', models.TextField()),
                ('html_url', models.TextField()),
                ('followers_url', models.TextField()),
                ('following_url', models.TextField()),
                ('gists_url', models.TextField()),
                ('starred_url', models.TextField()),
                ('subscriptions_url', models.TextField()),
                ('organizations_url', models.TextField()),
                ('repos_url', models.TextField()),
                ('events_url', models.TextField()),
                ('received_events_url', models.TextField()),
                ('type', models.TextField()),
                ('site_admin', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('followers', models.IntegerField()),
                ('repos', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('query', models.TextField(primary_key=True, serialize=False)),
                ('total_results', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='github',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubapp.Language'),
        ),
        migrations.AddField(
            model_name='github',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubapp.Location'),
        ),
        migrations.AddField(
            model_name='github',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubapp.Queries'),
        ),
        migrations.AddField(
            model_name='github',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
