# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='github',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
