# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0002_auto_20170926_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='githubapp.Language'),
        ),
        migrations.AlterField(
            model_name='github',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='githubapp.Location'),
        ),
        migrations.AlterField(
            model_name='github',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='githubapp.Queries'),
        ),
    ]
