# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0003_auto_20170926_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='user',
            field=models.TextField(),
        ),
    ]
