# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0004_auto_20170927_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='github',
            name='repos',
            field=models.IntegerField(null=True),
        ),
    ]
