# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0005_auto_20170927_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='repos',
        ),
        migrations.AddField(
            model_name='github',
            name='company',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='following',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='public_gists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='public_repos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='github',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
