# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubapp', '0006_auto_20170927_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='creation_date',
            new_name='created_date',
        ),
    ]
